### ISSUE TITLE
Error when launching the bubulle command

### ISSUE THREAD

**Issue by Team22052001** [aureliancnx/Bubulle-Norminette#19]
Hello, I've got this error when I'm launching the simple command :

```bash
Traceback (most recent call last):
  File "/usr/local/lib/bubulle/bubulle-py/bubulle.py", line 28, in <module>
    from args_handler import handle_args, parse_args, set_time_start
  File "/usr/local/lib/bubulle/bubulle-py/args_handler.py", line 28, in <module>
    from utils import version_utils
  File "/usr/local/lib/bubulle/bubulle-py/utils/version_utils.py", line 32, in <module>
    import file_utils
ModuleNotFoundError: No module named 'file_utils'
```
I tried to reinstall it but no effect (or success)...

**Comment by Axandel** [comment]
Hello, I have the same error on the last version

**Comment by CogalTek** [comment]
me too
`Traceback (most recent call last):
  File "/usr/local/lib/bubulle/bubulle-py/bubulle.py", line 28, in <module>
    from args_handler import handle_args, parse_args, set_time_start
  File "/usr/local/lib/bubulle/bubulle-py/args_handler.py", line 28, in <module>
    from utils import version_utils
  File "/usr/local/lib/bubulle/bubulle-py/utils/version_utils.py", line 32, in <module>
    import file_utils
ModuleNotFoundError: No module named 'file_utils'
`

**Comment by Axandel** [comment]
All tries of "import <module>" from the current directory does not work for more precision

**Comment by Beafowl-Pull** [comment]
same error

**Comment by Axandel** [comment]
A simple fix for all errors, open these files, and change some lines:

/usr/local/lib/bubulle/bubulle-py/utils/version_utils
(line 32) import file_utils ---> from . import file_utils

/usr/local/lib/bubulle/bubulle-py/utils/error_handling.py
(line 29) from string_utils import Colors ---> from .string_utils import Colors

/usr/local/lib/bubulle/bubulle-py/html_report/html_report.py
(line 33) from back_overview import HtmlReportOverview ---> from .back_overview import HtmlReportOverview
